services:
  db:
    image: postgres:15
    container_name: planit_db
    environment:
      POSTGRES_DB: planit_db
      POSTGRES_USER: planit_user
      POSTGRES_PASSWORD: planit_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: planit_web
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - DEBUG=True
      - DATABASE_ENGINE=postgresql
      - DATABASE_NAME=planit_db
      - DATABASE_USERNAME=planit_user
      - DATABASE_PASSWORD=planit_password
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      db:
        condition: service_started

volumes:
  postgres_data:
